openapi: 3.0.0
info:
  title: Gas & Water Usage Monitoring API
  description: API для мониторинга использования газа, холодной и горячей воды.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки

paths:
  /measurements:
    post:
      tags:
        - Measurement
      summary: Отправка текущих измерений
      description: Позволяет пользователю отправить текущие показания измерений.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementDto'
      responses:
        '201':
          description: Измерение успешно добавлено
        '400':
          description: Неверный запрос

  /measurements/{userId}:
    get:
      tags:
        - Measurement
      summary: Получение истории измерений
      description: Позволяет получить историю измерений для конкретного пользователя.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            format: int64
          description: Уникальный идентификатор пользователя
        - in: query
          name: page
          required: true
          schema:
            type: integer
            default: 0
          description: номер страницы
        - in: query
          name: size
          required: true
          schema:
            type: integer
            default: 10
          description: размер страницы
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeasurementPageableResponseDto'
        '404':
          description: Пользователь не найден

components:
  schemas:
    MeasurementDto:
      type: object
      required:
        - userId
        - type
        - value
      properties:
        userId:
          type: integer
          format: int64
          description: ID пользователя
        type:
          type: string
          description: Тип измерения (например, GAS, COLD_WATER)
        value:
          type: number
          format: double
          minimum: 0
          description: Значение измерения
        date:
          type: string
          format: date

    MeasurementPageableResponseDto:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: общее количестве элементов
        content:
          type: array
          items:
            $ref: '#/components/schemas/MeasurementDto'

